#include "hash_tables.h"
/**
 * key_index - ...
 * @key: ...
 *@size: ...
* Return: .....
*/
unsigned long int key_index(const unsigned char *key, unsigned long int size)
{
unsigned long int value = hash_djb2(key);
return (value % size);
}
